config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'pages#home'
  get 'pages/home'
  get 'pages/me'
  get 'pages/manage'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :posts
  resources :projects, only: [:index, :show, :new, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :photos, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :logo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_projects


  def set_projects
    @projects = Project.all
  end

  protected

  def after_sign_in_path_for(resource)
    pages_manage_path # Replace with the path you want to redirect to
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @posts = Post.all
  end

  def me
  end

  def manage
    @projects = Project.all
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def new
    @new_post = Post.new
  end

  def create
    @new_post = Post.new(post_params)
    if @new_post.save
      redirect
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, photos: [])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate_user!, only: [:index, :show]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @posts = @project.posts
  end

  def new
    @project = Project.new
  end

  def create
    # render plain: params[:project].inspect
    @project = Project.new(project_params)

    if @project.save
      redirect_to "/pages/manage"
    else
      render 'new'
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :logo)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    pages_manage_path # Or :prefix_to_your_route
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LxsDevblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>

    <%= render "shared/flashes" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="feed">
  <h1>Derniers Articles</h1>
  <% if @posts.exists? %>
    <%= @posts.each do |post| %>
      <div>
        <h2><%= post.title %></h2>
        <p><%= post.content %></p>
      </div>
    <% end %>
  <% else %>
    <p>Aucun article n'a été publié pour le moment.</p>
  <% end %>
</div>

app/views/pages/manage.html.erb
<div class="feed">
  <h1>Manage</h1>
  <%= link_to "Add Project", new_project_path, class:"manage-button" %>
  <%= link_to "New Post", new_post_path, class:"manage-button" %>
    <div class="manage-projects-showcase">
      <h2>Projets</h2>
      <% if @projects.exists? %>
        <% @projects.each do |project| %>
          <div class="manage-project-card">
            <h3><%= project.name %></h3>
            <%= image_tag "#{project.logo}" %>
            <%= button_to "Delete", project_path(project), class:"manage-button", method: :delete %>
          </div>
        <% end %>
      <% else %>
        <p>Aucun projet n'a été publié pour le moment.</p>
      <% end %>
    </div>
</div>

app/views/pages/me.html.erb
<h1>Pages#me</h1>
<p>Find me in app/views/pages/me.html.erb</p>

app/views/posts/_form.html.erb
<%= simple_form_for post, html: { data: { controller: "editor" } } do |f| %>
  <%= f.input :title %>
  <div id="post-content" data-editor-target="post_content">


  </div>
  <%= f.button :submit %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<div class="feed">
  <%= render 'posts/form', post: @new_post %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/projects/index.html.erb
<div class="feed">
    <div class="projects-showcase">
      <h2>Projets</h2>
      <% if @projects.exists? %>
        <% @projects.each do |project| %>
          <%= link_to project do  %>
            <div class="project-card">
              <h3><%= project.name %></h3>
              <%= image_tag "#{project.logo}" %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>Aucun projet n'a été publié pour le moment.</p>
      <% end %>
    </div>
</div>

app/views/projects/new.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :logo %>
  <%= f.button :submit %>
<% end %>

app/views/projects/show.html.erb
<div class="feed">
  <%= @project.name %>
  <% if @posts.exists? %>
    <% @posts.each do |post| %>
      <%= link_to post , class: 'container-link', block: true do %>
        <div class="post-card">
          <div class="post-title">
            <%= post.title %>
          </div>
          <div class="post-date">
            <%= time_ago_in_words post.created_at %>
          </div>
          <%= post.content %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p>Aucun post n'a été publié pour le moment.</p>
  <% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to "LXS.devblog", root_path, class: "navbar-title" %>
  <div class="navbar-menu">
    <div class="dropdown">
      <span>
        <%= link_to "Projets", projects_path, class: "navbar-item" %>
          </span>
            <div class="dropdown-content">
              <% @projects.each do |project| %>
                <%= link_to project.name, project_path(project), class:"login-button" %>
              <% end %>
            </div>
    </div>
  </div>
  <div class="navbar-login">
    <% if user_signed_in? %>
      <div class="dropdown">
        <span>Mouse over me</span>
        <div class="dropdown-content">
          <%= button_to "Logout", destroy_user_session_path, class:"login-button", method: :delete %>
          <%= link_to "Manage", pages_manage_path, class:"login-button" %>
        </div>
      </div>
    <% else %>
      <%= link_to "Login", user_session_path %>
    <% end %>


  </div>
</div>